index.html

fix the index

---

article/computer-and-information-technology.html
article/electronics-communication-control-and-instrumentation.html
article/mechanical-and-industrial-engineering.html
article/power-and-energy.html
article/remote-sensing-and-geomatics.html

fix the edas code by replacing the code

fix the edas link

---

article/computer-and-information-technology.html
article/electronics-communication-control-and-instrumentation.html
article/mechanical-and-industrial-engineering.html
article/power-and-energy.html
article/remote-sensing-and-geomatics.html

fix the edas code

---

index.html

fix the index page

---

article/physics-and-astronomy.html
article/symposia.html

physics and astro sympo

---

article/about.html

fix prof. omar name

---

article/about.html

hide publication info in about.html

hide publication info

---

article/about.html

fix prof. rohayu's afilliation

fix afilliation

---

article/symposia.html

Fix PIC name

---

article/about.html
article/computer-and-information-technology.html
article/symposia.html
index.html

fix the typo

---

article/fees.html

fix the fee for local presenter

fix the fee

---

article/computer-and-information-technology.html
article/electronics-communication-control-and-instrumentation.html
article/environmental-and-earth-science.html
article/material-sciences-and-chemistry.html
article/mechanical-and-industrial-engineering.html
article/physics-and-astronomy.html
article/power-and-energy.html
article/remote-sensing-and-geomatics.html
index.html

fix the publication matter

---

article/environmental-and-earth-science.html
article/physics-and-astronomy.html

fix the committee symposium

---

article/physics-and-astronomy.html

fix the committe symposium

---

article/environmental-and-earth-science.html

add the EES committeeMaster

---

article/about-ugm.html
article/about.html
article/abstract-submission-tutorial.html
article/account-registration-tutorial-non-presenters.html
article/account-registration-tutorial-presenters.html
article/author-guidelines.html
article/computer-and-information-technology.html
article/conference-program.html
article/downloads.html
article/electronics-communication-control-and-instrumentation.html
article/environmental-and-earth-science.html
article/fees.html
article/full-paper-submission-tutorial.html
article/material-sciences-and-chemistry.html
article/mechanical-and-industrial-engineering.html
article/payment-procedure.html
article/physics-and-astronomy.html
article/power-and-energy.html
article/presentation-guidelines.html
article/remote-sensing-and-geomatics.html
article/scientific-net.html
article/submissions.html
article/symposia.html
article/venue.html
index.html

drop abstract submission and activate submission

drop abstract submission and activate submission

---

article/author-guidelines.html

Fix the guideline

---

404.html
article/about-ugm.html
article/about.html
article/abstract-submission-tutorial.html
article/account-registration-tutorial-non-presenters.html
article/account-registration-tutorial-presenters.html
article/author-guidelines.html
article/computer-and-information-technology.html
article/conference-program.html
article/downloads.html
article/electronics-communication-control-and-instrumentation.html
article/environmental-and-earth-science.html
article/fees.html
article/full-paper-submission-tutorial.html
article/material-sciences-and-chemistry.html
article/mechanical-and-industrial-engineering.html
article/payment-procedure.html
article/physics-and-astronomy.html
article/power-and-energy.html
article/presentation-guidelines.html
article/remote-sensing-and-geomatics.html
article/scientific-net.html
article/submissions.html
article/symposia.html
article/venue.html
index.html

change the CP and fix the guidelines page

change the CP and fix the guidelines page

---

404.html
article/about-ugm.html
article/about.html
article/abstract-submission-tutorial.html
article/account-registration-tutorial-non-presenters.html
article/account-registration-tutorial-presenters.html
article/author-guidelines.html
article/computer-and-information-technology.html
article/conference-program.html
article/downloads.html
article/electronics-communication-control-and-instrumentation.html
article/environmental-and-earth-science.html
article/fees.html
article/full-paper-submission-tutorial.html
article/material-science-and-chemistry.html
article/mechanical-and-industrial-engineering.html
article/payment-procedure.html
article/physics-and-astronomy.html
article/power-and-energy.html
article/presentation-guidelines.html
article/remote-sensing-and-geomatics.html
article/submissions.html
article/symposia.html
article/venue.html
index.html

add ieee and scopus

---

404.html
index.html
index.php

fix the 404 and index

---

article/downloads.html

fix footer

---

index.html

add the notification

---

article/about-ugm.html
article/about.html
article/abstract-submission-tutorial.html
article/account-registration-tutorial-non-presenters.html
article/account-registration-tutorial-presenters.html
article/author-guidelines.html
article/computer-and-information-technology.html
article/conference-program.html
article/downloads.html
article/electronics-communication-control-and-instrumentation.html
article/environmental-and-earth-science.html
article/fees.html
article/full-paper-submission-tutorial.html
article/ieee.html
article/material-science-and-chemistry.html
article/mechanical-and-industrial-engineering.html
article/payment-procedure.html
article/power-and-energy.html
article/presentation-guidelines.html
article/publications.html
article/remote-sensing-and-geomatics.html
article/submissions.html
article/symposia.html
article/uasc-proceedings.html
article/venue.html
index.html

fix the typo and drop uasc proceedings

fix the typo and drop uasc proceedings

---

article/about-ugm.html
article/about.html
article/abstract-submission-tutorial.html
article/account-registration-tutorial-non-presenters.html
article/account-registration-tutorial-presenters.html
article/author-guidelines.html
article/computer-and-information-technology.html
article/conference-program.html
article/downloads.html
article/electronics-communication-control-and-instrumentation.html
article/environmental-and-earth-science.html
article/fees.html
article/full-paper-submission-tutorial.html
article/ieee.html
article/material-science-and-chemistry.html
article/mechanical-and-industrial-engineering.html
article/payment-procedure.html
article/power-and-energy.html
article/presentation-guidelines.html
article/publications.html
article/remote-sensing-and-geomatics.html
article/submissions.html
article/symposia.html
article/uasc-proceedings.html
article/venue.html
index.html

fix some pages

---

article/publications.html

fix publication page

---

index.html

Remove * from E3S

---

article/submissions.html

disable the register for non-presenter

disable the register for non-presenter

---

article/environmental-and-earth-science.html

fix the editor's name and typo

fix the editor's name and typo

---

article/material-science-and-chemistry.html

add commitee of material science and chemistry

add commitee of material science and chemistry

---

index.html

remove notification

---

article/payment-confirmation-non-presenter.html
article/payment-confirmation-presenter.html

add payment confirmation page

---

article/submissions.html

activate TTP submit button

---

article/ttp-confirmation.html

add ttp confirmation

---

article/ttp-account-activation-request.html

replace ttp account activation

replace ttp account activation

---

article/ttp-account-activation-request.html

for ttp account activation request

change jotform to google form

---

article/conference-program.html

New layout for parallel speakers in conference-program.html

Update conference program

---

article/ieee.html
article/publications.html

update ieee and publications
